// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmD_CUNts0xOJvXGVm3VGoX5cAgyTdZo',
    appId: '1:647957279975:web:78d60e15bbb66f8b075e42',
    messagingSenderId: '647957279975',
    projectId: 'multivendorapp-5f78e',
    authDomain: 'multivendorapp-5f78e.firebaseapp.com',
    databaseURL: 'https://multivendorapp-5f78e-default-rtdb.firebaseio.com',
    storageBucket: 'multivendorapp-5f78e.appspot.com',
    measurementId: 'G-KPELCW9V9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBniMlEQOZe9W24LJfY-LRWV9FF0bPv4gA',
    appId: '1:647957279975:android:fc394df9bde69cfe075e42',
    messagingSenderId: '647957279975',
    projectId: 'multivendorapp-5f78e',
    databaseURL: 'https://multivendorapp-5f78e-default-rtdb.firebaseio.com',
    storageBucket: 'multivendorapp-5f78e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtt8_KZsCYGCH6f2SgeCjTMdqJNNj0rbs',
    appId: '1:647957279975:ios:c102dadfc4b63648075e42',
    messagingSenderId: '647957279975',
    projectId: 'multivendorapp-5f78e',
    databaseURL: 'https://multivendorapp-5f78e-default-rtdb.firebaseio.com',
    storageBucket: 'multivendorapp-5f78e.appspot.com',
    androidClientId: '647957279975-0ea6h7b9ra99p7g7hgaab7juiqhhguvr.apps.googleusercontent.com',
    iosClientId: '647957279975-027fqllkp51g9a6e07r8djj1nhmbf9i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceappwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtt8_KZsCYGCH6f2SgeCjTMdqJNNj0rbs',
    appId: '1:647957279975:ios:c102dadfc4b63648075e42',
    messagingSenderId: '647957279975',
    projectId: 'multivendorapp-5f78e',
    databaseURL: 'https://multivendorapp-5f78e-default-rtdb.firebaseio.com',
    storageBucket: 'multivendorapp-5f78e.appspot.com',
    androidClientId: '647957279975-0ea6h7b9ra99p7g7hgaab7juiqhhguvr.apps.googleusercontent.com',
    iosClientId: '647957279975-027fqllkp51g9a6e07r8djj1nhmbf9i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceappwithfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAGuVcJV9k91ci2UbkcdgzM0fn3UoNOZQ',
    appId: '1:647957279975:web:ff48f6a5387a3f70075e42',
    messagingSenderId: '647957279975',
    projectId: 'multivendorapp-5f78e',
    authDomain: 'multivendorapp-5f78e.firebaseapp.com',
    databaseURL: 'https://multivendorapp-5f78e-default-rtdb.firebaseio.com',
    storageBucket: 'multivendorapp-5f78e.appspot.com',
    measurementId: 'G-QVGFF442YC',
  );

}